import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import CursorEffects from "@/components/CursorEffects"; // Import the new component

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Umar Dev",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
          rel="stylesheet"
        />
        <script src="https://unpkg.com/typed.js@2.1.0/dist/typed.umd.js"></script>
      </head>
      <body className={inter.className}>
          <div className="cursor-dot" data-cursor-dot></div>
          <div className="cursor-outline" data-cursor-outline></div>
        <CursorEffects /> 
        <Navbar />
        {children}
      </body>
    </html>
  );
}
